title: Math Notes
description: Notes on algebra, probability theory, and linear algebra
theme: jekyll-theme-minimal

kramdown:
  math_engine: mathjax

defaults:
  - scope:
      path: "notes/algebra"
    values:
      layout: default
      sidebar: algebra
      section: algebra
  - scope:
      path: "notes/probability"
    values:
      layout: default
      sidebar: probability
      section: probability
  - scope:
      path: "notes/linear_algebra"
    values:
      layout: default
      sidebar: linear_algebra
      section: linear_algebra
